name: Auto-generate Markdown

on:
  workflow_call:
  workflow_dispatch:

jobs:
  markdown-autodocs:
    name: Auto-generate Markdown
    runs-on: ubuntu-latest

    steps:
      - name: Markdown autodocs
        - uses: dineshsonachalam/markdown-autodocs@v1.0.7
          with:
            # Optional, defaults to author of the commit that triggered the run
            commit_author: Kyle Tse <shtse8@gmail.com>

            # Optional, defaults to "actions@github.com"
            commit_user_email: shtse8@gmail.com

            # Optional, but recommended
            # Defaults to "Apply automatic changes"
            commit_message: Apply automatic changes

            # Optional output file paths, defaults to '[./README.md]'.
            output_file_paths: '[./README.md]'

            # Categories to automatically sync or transform its contents in the markdown files.
            # Defaults to '[code-block,json-to-html-table,workflow-artifact-table]'
            categories: '[code-block,json-to-html-table,workflow-artifact-table]'