name: Auto-generate Markdown

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_call:
  workflow_dispatch:

jobs:
  markdown-autodocs:
    name: Auto-generate Markdown
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generated Markdown Readmes
        uses: DaanV2/Markdown-Action-Create-Indexes@v2.0.0