name: Auto-generate Markdown

on:
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  markdown-autodocs:
    name: Auto-generate Markdown
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Generated Markdown Readmes
        uses: DaanV2/Markdown-Action-Create-Indexes@v2.0.0
        
      - uses: EndBug/add-and-commit@v9
        with:
          message: "Auto-generate Markdown"
          signoff: true
          push: true
          force: true